import { UserPlan, PlanTemplate } from '@/types/templo/salud';

export const MOCK_PLANES: UserPlan[] = [
  {
    id: 'up_1',
    templateId: 'plan_ejercicio_1',
    category: 'ejercicio',
    difficulty: 3,
    progress: 33,
    bestScore: 80,
    active: true,
    createdAt: new Date(),
    title: 'Abdominales Intermedios',
    durationDays: 15,
    currentDay: 5,
    totalDays: 15,
  },
  {
    id: 'up_2',
    templateId: 'plan_alimentacion_1',
    category: 'alimentacion',
    difficulty: 2,
    progress: 8,
    bestScore: 14,
    active: true,
    createdAt: new Date(),
    title: 'Ayuno de Daniel',
    durationDays: 38,
    currentDay: 3,
    totalDays: 38,
  },
  {
    id: 'up_3',
    templateId: 'plan_espiritualidad_1',
    category: 'espiritualidad',
    difficulty: 4,
    progress: 58,
    bestScore: 100,
    active: true,
    createdAt: new Date(),
    title: 'La Biblia en 1 Año',
    durationDays: 365,
    currentDay: 212,
    totalDays: 365,
  },
];

export const MOCK_TEMPLATES: PlanTemplate[] = [
  {
    id: 'plan_ejercicio_1',
    title: 'Abdominales Intermedios',
    category: 'ejercicio',
    difficulty: 3,
    durationDays: 15,
    description: 'Rutina progresiva de core para nivel intermedio. Incluye variantes de abdominales, plancha y descansos activos.',
    days: [
      { day: 1, order: 1, title: 'Crunch básico', type: 'ejercicio', reps: 15 },
      { day: 1, order: 2, title: 'Plancha', type: 'ejercicio', durationSec: 30 },
      { day: 1, order: 3, title: 'Descanso', type: 'ejercicio', restSec: 10 },
      { day: 1, order: 4, title: 'Bicicleta', type: 'ejercicio', reps: 20 },
    ],
  },
  {
    id: 'plan_alimentacion_1',
    title: 'Ayuno de Daniel',
    category: 'alimentacion',
    difficulty: 2,
    durationDays: 21,
    description: 'Basado en Daniel 1:12. Solo vegetales, frutas, legumbres y agua. Sin carne, sin vino, sin manjares.',
    days: [
      { day: 1, order: 1, title: 'Desayuno: Avena con frutas', type: 'alimentacion', description: 'Avena cocida con manzana y canela, sin azúcar.' },
      { day: 1, order: 2, title: 'Almuerzo: Legumbres', type: 'alimentacion', description: 'Lentejas con verduras al vapor.' },
    ],
  },
  {
    id: 'plan_espiritualidad_1',
    title: 'La Biblia en 1 Año',
    category: 'espiritualidad',
    difficulty: 4,
    durationDays: 365,
    description: 'Lectura completa de la Biblia en un año. Incluye reflexión diaria y versículo de memoria.',
    days: [
      { day: 1, order: 1, title: 'Génesis 1-3', type: 'espiritualidad', passage: 'Génesis 1-3', verse: '"En el principio creó Dios los cielos y la tierra." — Gn 1:1', reflection: 'Reflexiona sobre el poder creador de Dios y tu lugar en Su creación.' },
    ],
  },
];